---
- name: install environment for use by "Ton private plugin TEST"
  hosts: localhost
  gather_facts: true

  tasks:

# TEST CO specific parameter
    - name: test receipt of CO parameter
      debug:
        msg: "TON_TEST ={{ TON_TEST }}="
      when: TON_TEST is defined

    - name: signal variable not found
      debug:
        msg: "variable TON_TEST not defined"
      when: TON_TEST is undefined

# TEST CO vault secret parameter

    - name: test1 receipt of CO VAULT parameter
      debug:
        msg: "TON_SECRET ={{ TON_SECRET }}="
      when: TON_SECRET is defined

    - name: signal variable not found
      debug:
        msg: "variable TON_SECRET not defined"
      when: TON_SECRET is undefined


    - name: test2 receipt of CO VAULT parameter
      debug:
        msg: "secret2 ={{ secret2 }}="
      when: secret2 is defined

    - name: signal variable not found
      debug:
        msg: "variable secret2 not defined"
      when: secret2 is undefined

#  roles:
#    - python
#    - pyenv
#    - uwsgi
#    - flask-app
#    - camunda-server
#    - role: userspace_applications
#      vars:
#        - list_userspace_applications:
#          - "05-python-3.9"
#          - "10-python-poetry"
#          - "70-tweets-collector"
#          - "999ready"

